#!/usr/bin/env node
/**
 * Self-host the Mozilla PDF.js viewer at public/pdfjs/ for the in-page split
 * compare-view. The viewer is a same-origin static asset (no X-Frame-Options
 * issue), and PDF.js fetches the actual PDF via XHR. To pass the browser CORS
 * check we point it at https://export.arxiv.org/pdf/<id>.pdf which sets
 * `Access-Control-Allow-Origin: *`.
 *
 * pdfjs-dist on npm (>= v3) ships only the component library, not the
 * standalone viewer.html. The complete prebuilt viewer lives in the GitHub
 * release zip, so we download that on first build and cache it under
 * node_modules/.cache/.
 *
 * Run by the `prebuild` / `predev` npm hooks. Idempotent: skips work if
 * public/pdfjs/web/viewer.html already exists.
 */
import { execSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const VERSION = "4.10.38";
const URL = `https://github.com/mozilla/pdf.js/releases/download/v${VERSION}/pdfjs-${VERSION}-dist.zip`;

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dest = join(root, "public/pdfjs");
const viewerSentinel = join(dest, "web/viewer.html");
const cacheDir = join(root, "node_modules/.cache");
const cacheZip = join(cacheDir, `pdfjs-${VERSION}-dist.zip`);

if (existsSync(viewerSentinel)) {
  console.log("✓ pdfjs viewer already in public/pdfjs/, skipping download");
  process.exit(0);
}

mkdirSync(cacheDir, { recursive: true });

if (!existsSync(cacheZip)) {
  console.log(`↓ downloading pdfjs v${VERSION} from GitHub releases...`);
  try {
    execSync(`curl -fsSL "${URL}" -o "${cacheZip}"`, { stdio: "inherit" });
  } catch (e) {
    console.error("✗ failed to download pdfjs zip:", e.message);
    console.error("  Are you offline / firewalled? URL:", URL);
    process.exit(1);
  }
}

if (existsSync(dest)) rmSync(dest, { recursive: true });
mkdirSync(dest, { recursive: true });

console.log(`⊞ extracting → public/pdfjs/`);
try {
  execSync(`unzip -q "${cacheZip}" -d "${dest}"`, { stdio: "inherit" });
} catch (e) {
  console.error("✗ failed to unzip pdfjs zip:", e.message);
  console.error("  Is `unzip` installed on this system?");
  process.exit(1);
}

// Patch: disable PDF.js' built-in validateFileURL same-origin check. By
// default the viewer rejects ?file=<url> when the file origin doesn't match
// the viewer's, except for hard-coded mozilla.github.io. We *want* to load
// PDFs from export.arxiv.org (which we have whitelisted via CORS), so make
// the check a no-op. This is safe in our context because the file param is
// always generated by our own Astro page — never user input.
const viewerMjs = join(dest, "web/viewer.mjs");
if (existsSync(viewerMjs)) {
  const before = readFileSync(viewerMjs, "utf8");
  const needle = `var validateFileURL = function (file) {\n    if (!file) {\n      return;\n    }`;
  const replacement = `var validateFileURL = function (file) {\n    return; // patched: cross-origin allowed (we trust our own ?file= param)\n    if (!file) {\n      return;\n    }`;
  if (!before.includes(needle)) {
    console.warn(
      "⚠  could not locate validateFileURL needle in viewer.mjs — origin check NOT patched.",
    );
    console.warn("   The viewer may reject cross-origin ?file= URLs at runtime.");
  } else {
    writeFileSync(viewerMjs, before.replace(needle, replacement));
    console.log("✎ patched viewer.mjs to allow cross-origin ?file= URLs");
  }
}

const walk = (dir) => {
  let count = 0,
    bytes = 0;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      const sub = walk(full);
      count += sub.count;
      bytes += sub.bytes;
    } else {
      count += 1;
      bytes += st.size;
    }
  }
  return { count, bytes };
};
const { count, bytes } = walk(dest);
const mb = (bytes / 1024 / 1024).toFixed(1);
console.log(`✓ pdfjs viewer ready  (${count} files, ${mb} MB)  at public/pdfjs/web/viewer.html`);
